// client/src/contexts/LanguageContext.js (with enhanced translations)
import React, { createContext, useState, useContext, useEffect } from 'react';

// Create translation files for English and Vietnamese
const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    warehouse: "Warehouse",
    employees: "Employees",
    requests: "Requests",
    production: "Production",
    
    // Notifications
    notifications: "Notifications",
    markAllAsRead: "Mark all as read",
    noNotifications: "No notifications",
    viewAllNotifications: "View all notifications",
    allNotificationsRead: "All notifications marked as read",
    markAsRead: "Mark as read",
    allNotifications: "All notifications",
    unread: "Unread",
    notificationsList:"Notifications list",
    requestNotifications: "Request notifications",
    systemNotifications: "System notifications",
    relatedRequest:"Related request",
    requestInfoNotAvailable:"Request information is not available",
    noRequestDataAvailable: 'Request data is not available',
    addMaterialRequestApproved: "Your request to add material has been approved",
    editMaterialRequestApproved: "Your request to edit material has been approved",
    deleteMaterialRequestApproved: "Your request to delete material has been approved",
    addMaterialRequestRejected: "Your request to add material has been rejected",
    editMaterialRequestRejected: "Your request to edit material has been rejected",
    deleteMaterialRequestRejected: "Your request to delete material has been rejected",
    newMaterialRequest: "New material request from",
    yourRequestApproved: "Your {requestType} material request has been approved",
    yourRequestRejected: "Your {requestType} material request has been rejected",
    
    // Toast messages
    loginSuccess: "Login successful",
    logoutSuccess: "Logged out successfully",
    materialAdded: "Material added successfully",
    materialUpdated: "Material updated successfully",
    materialDeleted: "Material deleted successfully",
    requestSubmitted: "Request submitted successfully",
    requestApproved: "Request approved successfully",
    requestRejected: "Request rejected successfully",
    operationSuccess: "Operation completed successfully",
    operationFailed: "Operation failed",
    validationError: "Please correct the errors",
    networkError: "Network error. Please try again",
    serverError: "Server error. Please try again later",
    materialAddFailed: "Failed to add material",
    materialUpdateFailed: "Failed to update material",
    materialDeleteFailed: "Failed to delete material",
    requestSubmitFailed: "Failed to submit request",
    requestProcessFailed: "Failed to process request",
    notesSavedSuccessfully: "Notes saved successfully",
    errorSavingNotes: "Error saving notes",
    errorFetchingAssemblyDetails: "Error loading assembly details",

    // Dashboard
    totalMaterials: "Total Materials",
    suppliers: "Suppliers",
    thisWeeksOrders: "This Week's Orders",
    systemUsers: "System Users",
    materialTypesDistribution: "Material Types Distribution",
    monthlyInventoryChanges: "Monthly Inventory Changes",
    recentlyUpdatedMaterials: "Recently Updated Materials",
    viewAllMaterials: "View All Materials",
    quickActions: "Quick Actions",
    manageMaterials: "Manage Materials",
    exportInventoryReport: "Export Inventory Report",
    registerNewShipment: "Register New Shipment",
    addNewUser: "Add New User",

    // Materials
    materialsList: "Materials List",
    searchByPacketNo: "Search by Packet No",
    searchByPartName: "Search by Part Name",
    searchBySupplier: "Search by Supplier",
    searchByUpdatedBy: "Search by Updated By",
    searchBy: "Search by",
    addMaterial: "Add Material",
    requestAdd: "Request Add",
    packetNo: "Packet No",
    partName: "Part Name",
    materialCode: "Material Code",
    length: "Thickness",
    width: "Width",
    materialType: "Material Type",
    quantity: "Quantity",
    supplier: "Supplier",
    updatedBy: "Updated By",
    lastUpdated: "Last Updated",
    materialDetails: "Material Details",
    close: "Close",
    cancel: "Cancel",
    delete: "Delete",
    saveChanges: "Save Changes",
    adding: "Adding...",
    saving: "Saving...",
    deleting: "Deleting...",
    editMaterial: "Edit Material",
    requestEdit: "Request Edit",
    requestDelete: "Request Delete",
    confirmDelete: "Confirm Delete",
    materialDeleteConfirm: "Are you sure you want to delete this material?",
    submit: "Submit",
    submitting: "Submitting...",
    requestDetails: "Request to {requestType} Material",
    materialQRCode: "Material QR Code: {materialName}",
    scanQRCode: "Scan this QR code to view material details:",
    print: "Print",
    edit: "Edit",
    generate: "Generate",
    generateQRCode: "Generate QR Code",
    "is required": "is required",
    "This packet number already exists. Packet numbers must be unique.": "This packet number already exists. Packet numbers must be unique.",
    "Fill in the details for your": "Fill in the details for your",
    "add": "add",
    "request": "request",
    "This request will be sent to an administrator for approval.": "This request will be sent to an administrator for approval.",
    

    // Requests
    materialRequests: "Material Requests",
    status: "Status",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    id: "ID",
    type: "Type",
    materialID: "Material ID",
    user: "User",
    requestDate: "Request Date",
    actions: "Actions",
    viewDetails: "View Details",
    approve: "Approve",
    reject: "Reject",
    requestInformation: "Request Information",
    requestedBy: "Requested By",
    responseDate: "Response Date",
    processedBy: "Processed By",
    adminNotes: "Admin Notes",
    requestData: "Request Data",
    processRequest: "Process This Request",
    decision: "Decision",
    notes: "Notes (Optional)",
    notesPlaceholder: "Explain your decision (will be visible to the requester)",
    approveRequest: "Approve Request",
    rejectRequest: "Reject Request",
    processing: "Processing...",
    "Request ID": "Request ID",
    "Error loading requests": "Error loading requests",
    "requests found": "requests found",
    "No": "No",
    "Request Details": "Request Details",
    "No request data available": "No request data available",
    "Error parsing request data": "Error parsing request data",
    "Raw data type": "Raw data type",
    "First 100 chars": "First 100 chars",
    "No request selected": "No request selected",
    "Error processing request": "Error processing request",

    // Users
    usersList: "Users List",
    searchByName: "Search users by name",
    addUser: "Add User",
    username: "Username",
    fullName: "Full Name",
    role: "Role",
    phone: "Phone",
    userDetails: "User Details",
    editUser: "Edit User",
    password: "Password",
    passwordEdit: "Password (Leave blank to keep current)",
    phoneNumber: "Phone Number",
    createdAt: "Created At",
    "Adding...": "Adding...",
    "Password is required for new users": "Password is required for new users",
    "You don't have permission to delete this user": "You don't have permission to delete this user",
    "User not found": "User not found",
    "Error loading user details": "Error loading user details",
    "Are you sure you want to delete this user?": "Are you sure you want to delete this user?",

    // Login
    inventoryManagement: "Inventory Management",
    loginCredentials: "Enter your credentials to access the system",
    loggingIn: "Logging in...",
    login: "Login",

    // Common
    noRecordsFound: "No records found",
    loading: "Loading...",
    error: "Error",
    retry: "Retry",
    dimensions: "Dimensions",
    noData: "No data available",
    
    // Language
    language: "Language",
    english: "English",
    vietnamese: "Vietnamese",
    logout: "Logout",

    // Warehouse
    warehouseItems: "Warehouse Items",
    
    // Table common terms
    // noRecordsFound: "No records found",
    filter: "Filter",
    search: "Search",
    
    // Notifications
    newRequestNotification: "New {requestType} material request from {username}",
    requestProcessedNotification: "Your {requestType} material request has been {status}",
    
    // Buttons
    create: "Create",
    update: "Update",
    detail: "Detail",
    confirmAction: "Confirm",
    backToList: "Back to List",
    
    // Batch Grouping Page
    batchGrouping: "Batch Grouping",
    group: "Group",
    ungroupedBatches: "Ungrouped Batches",
    groupedBatches: "Grouped Batches",
    noUngroupedBatches: "No ungrouped batches found",
    noGroupedBatches: "No grouped batches found",
    warehouseEntryTime: "Warehouse Entry Time",
    groupNo: "No",
    confirmGrouping: "Confirm Batch Grouping",
    confirmGroupingMessage: "Are you sure you want to group the selected batches?",
    selectedBatchesCount: "Selected batch count",
    afterGroupingStatus: "After grouping, the status of these batches will be updated to \"Grouped for Assembly\"",
    batchQRCode: "Batch QR Code",
    batchDetails: "Batch Details",
    details: "Details",
    confirmAssembly: "Confirm Assembly for this Group?",
    pleaseEnterPIC: "Please enter PIC name:",
    selectPIC: "Select PIC",
    startTime: "Start time:",
    currentTime: "(current time)",
    completionTime: "Completion time:",
    plus1Hour: "+1 hour",
    plus2Hours: "+2 hours",
    plus4Hours: "+4 hours",
    plus8Hours: "+8 hours",
    custom: "Custom",
    estimatedCompletionTime: "Estimated completion time",
    productQuantity: "Product quantity:",
    confirm: "Confirm",
    groupDetails: "Details for Group #{groupId}",
    PIC: "PIC:",
    finishAndProceedToPlating: "Finish and proceed to plating",
    
    // New additions for batch grouping and production
    processProgress: "Production Process Progress",
    ungrouped: "Ungrouped",
    grouped: "Grouped",
    assembly: "Assembly",
    plating: "Plating",
    completed: "Completed",
    groupQRCode: "Group QR Code",
    groupQR: "Group QR",
    generateGroupQRCode: "Generate Group QR Code",
    assembledBy: "Assembled by",
    assemblyDate: "Assembly date",
    totalQuantity: "Total quantity",
    batchCount: "Batch count",
    groupContents: "Group Contents",
    pendingBatches: "Pending Batches",

    // New additions for production
    progress: "Progress",
    stageBatches: "Stage Batches",
    productionDetails: "Production Details",
    platingDetails: "Plating Details",
    machineName: "Machine Name",
    moldCode: "Mold Code",
    expectedOutput: "Expected Output",
    actualOutput: "Actual Output",
    startDate: "Start Date",
    endDate: "End Date",
    timePerBatch: "Time per batch",
    estimatedCompletion: "Estimated completion time",
    batchesDone: "Batches completed",
    batchesRemaining: "Batches remaining",
    setPlatingTime: "Set Plating Time",
    platingDate: "Plating Date",
    platingTime: "Plating Time",
    waitingForPlating: "Waiting for Plating",
    inPlatingProcess: "In Plating Process",
    timeEstimation: "Time Estimation",
    completePlating: "Complete Plating",
    completionDate: "Completion Date",

    // New translations for updated BatchGrouping.js
    basicAssemblyInfo: "Basic Assembly Information",
    productInfoAfterAssembly: "Product Information After Assembly",
    productName: "Product Name",
    productCode: "Product Code",
    enterProductName: "Enter product name...",
    enterProductCode: "Enter product code...",
    enterNotes: "Enter notes...",
    pleaseSelectCompletionTime: "Please select completion time",
    hours: "Hours",
    minutes: "Minutes",
    noProductName: "No product name",
    noProductCode: "No product code",
    assemblyInfo: "Assembly Information",
    assemblyComponents: "Assembly Components",
    confirmPlating: "Confirm Proceeding to Plating",
    confirmPlatingMessage: "Are you sure you want to proceed group #{groupId} to plating?",
    notesWillBeTransferredToPlating: "These notes will be transferred to the plating process",
    
    // Validation & Success Messages
    pleaseSelectAtLeastOneBatch: "Please select at least one batch to group",
    batchesGroupedSuccessfully: "Batches grouped successfully",
    errorGroupingBatches: "Error occurred while grouping batches",
    pleaseSelectPIC: "Please select a PIC",
    pleaseEnterProductQuantity: "Please enter product quantity",
    pleaseEnterProductName: "Please enter product name",
    pleaseEnterProductCode: "Please enter product code",
    pleaseEnterCompletionTime: "Please enter completion time",
    assemblyCreatedSuccessfully: "Assembly created successfully",
    errorCreatingAssembly: "Error occurred while creating assembly",
    successfullyProceededToPlating: "Successfully proceeded to plating",
    errorProceedingToPlating: "Error occurred while proceeding to plating",
    failedToFetchBatches: "Failed to fetch batches",
    pleaseSelectPlatingDateAndTime: "Please select plating date and time",
    pleaseSelectAtLeastOneBatchForPlating: "Please select at least one batch for plating",
    platingInfoUpdatedSuccessfully: "Plating information updated successfully",
    errorUpdatingPlatingInfo: "Error updating plating information",

    // For English translations
    warehouseReport: "Warehouse Inventory Report",
    dateRange: "Date Range",
    fromDate: "From",
    toDate: "To",
    apply: "Apply",
    dateFilterApplied: "Date filter applied successfully",
    exportAs: "Export as",
    pdfExportSuccess: "PDF exported successfully",
    csvExportSuccess: "CSV exported successfully",
    pdfExportFailed: "Failed to export PDF",
    csvExportFailed: "Failed to export CSV",
    preparingReport: "Preparing report...",
    templateWillInclude: "Template will include {count} fields",
    more: "more",
    enterTemplateName: "Please enter a template name",
    templateSaved: "Template saved successfully",
    warehouseLocation: "Warehouse Location",
    shelfNumber: "Shelf Number",
    binNumber: "Bin Number",
    storageConditions: "Storage Conditions",
    reportPreview: "Report Preview",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    last30Days: "Last 30 Days",
    thisQuarter: "This Quarter",
    monthlyReportTemplate: "Monthly Report Template",
    locationFields: "Location Fields",

    "Kiểm kho": "Stock Check",
    "Bắt đầu kiểm kho": "Start Stock Check",
    "Hoàn thành": "Finish",
    "Quét mã QR": "Scan QR Code",
    "Quét mã QR hoặc nhập mã nguyên vật liệu": "Scan QR code or enter material ID",
    "Quét": "Scan",
    "Đặt con trỏ vào ô nhập liệu này trước khi quét": "Place cursor in this input field before scanning",
    "Bạn không cần phải nhấp vào ô nhập liệu. Chỉ cần quét trực tiếp mã QR trên vật liệu.": "You don't need to click the input field. Just scan the QR code directly on the material.",
    "Sẵn sàng quét": "Ready to scan",
    "Sẵn sàng nhận dữ liệu từ máy quét...": "Ready to receive scanner data...",
    "Tổng kết kiểm kho": "Stock Check Summary",
    "Tổng số nguyên vật liệu": "Total Materials",
    "Đã kiểm tra": "Checked",
    "Chưa kiểm tra": "Unchecked",
    "Xem danh sách chưa kiểm tra": "View Unchecked List",
    "Kiểm tra lại": "Check Again",
    "Tìm kiếm nguyên vật liệu": "Search Materials",
    "Không tìm thấy nguyên vật liệu. Vui lòng thử lại": "Material not found. Please try again",
    "Nguyên vật liệu đã kiểm tra": "Material already checked",
    "Lỗi khi quét mã QR. Vui lòng thử lại.": "Error scanning QR code. Please try again.",
    "đã được kiểm tra": "has been checked",
    "Trạng thái": "Status",

    // Product Warehouse
    productWarehouse: "Product Warehouse",
    searchProducts: "Search products",
    qualityStatus: "Quality Status",
    defectCount: "Defect Count",
    usableCount: "Usable Count",
    statusUpdatedSuccessfully: "Status updated successfully",
    errorUpdatingStatus: "Error updating status",
    pleaseSelectStatus: "Please select a status",
    pleaseEnterQrCode: "Please enter QR code",
    invalidQrData: "Invalid QR data",
    invalidQrFormat: "Invalid QR format",
    productDataNotFound: "Product data not found",
    errorFetchingProductDetails: "Error fetching product details",
    scanQrCode: "Scan QR Code",
    generateQrCode: "Generate QR Code",
    qualityCheck: "Quality Check",
    waitingForCheck: "Waiting for Check",
    shipped: "Shipped",
    reserved: "Reserved",
    inStock: "In Stock",
    defective: "Defective",
    
    // Product Detail
    backToWarehouse: "Back to Warehouse",
    productNotFound: "Product Not Found",
    productDoesNotExist: "This product does not exist",
    productDetails: "Product Details",
    manufacturingInfo: "Manufacturing Information",
    groupId: "Group ID",
    createdBy: "Created By",
    overview: "Overview",
    materialInfo: "Material Information",
    productionInfo: "Production Information",
    assemblyInfo: "Assembly Information",
    platingInfo: "Plating Information",
    manufacturingTimeline: "Manufacturing Timeline",
    rawMaterial: "Raw Material",
    material: "Material",
    machine: "Machine",
    finalProduct: "Final Product",

    // Product Warehouse - Additional translations
    productName: "Product Name",
    productCode: "Product Code",
    quantity: "Quantity",
    status: "Status",
    qualityStatus: "Quality Status",
    defectCount: "Defect Count",
    usableCount: "Usable Count",
    waitingForCheck: "Waiting for Check",
    ok: "OK",
    ng: "NG",
    shipped: "Shipped",
    reserved: "Reserved",
    inStock: "In Stock",
    defective: "Defective",
    all: "All",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    last30Days: "Last 30 Days",
    filterByStatus: "Filter by Status",
    filterByDate: "Filter by Date",
    searchPlaceholder: "Search by product name or code...",
    noProductsFound: "No products found",
    productDetails: "Product Details",
    updateStatus: "Update Status",
    save: "Save",
    cancel: "Cancel",
    generateQR: "Generate QR",
    scanQR: "Scan QR",
    enterQRCode: "Enter QR Code",
    submit: "Submit",
    qualityCheck: "Quality Check",
    qualityCheckStatus: "Quality Check Status",
    qualityCheckDate: "Quality Check Date",
    qualityCheckBy: "Quality Check By",
    qualityCheckNotes: "Quality Check Notes",
    manufacturingDate: "Manufacturing Date",
    manufacturingBy: "Manufactured By",
    assemblyDate: "Assembly Date",
    assemblyBy: "Assembled By",
    platingDate: "Plating Date",
    platingBy: "Plated By",
    completionDate: "Completion Date",
    completionBy: "Completed By",
    history: "History",
    notes: "Notes",
    noHistory: "No history available",
    noNotes: "No notes available",
    statusHistory: "Status History",
    date: "Date",
    changedBy: "Changed By",
    fromStatus: "From Status",
    toStatus: "To Status",
    reason: "Reason",
    noStatusHistory: "No status history available",
    finishedProducts: "Finished Products",
    reportSettings: "Report Settings",
    allStatuses: "All Statuses",
    statusOK: "OK",
    statusNG: "NG",
    statusPending: "Pending",
    statusShipped: "Shipped",
    statusReserved: "Reserved",
    allDates: "All Dates",
    lastWeek: "Last Week",
    lastMonth: "Last Month",
    resetFilters: "Reset Filters",
    batchId: "Batch ID",
    currentStatus: "Current Status",
    newStatus: "New Status",
    statusInStock: "In Stock",
    statusDefective: "Defective",
    saveStatus: "Save Status",
    productHistory: "Product History",
    materialInformation: "Material Information",
    materialName: "Material Name",
    noMaterialInformation: "No material information available",
    productionInformation: "Production Information",
    mold: "Mold",
    operator: "Operator",
    noProductionInformation: "No production information available",
    assemblyInformation: "Assembly Information",
    noAssemblyInformation: "No assembly information available",
    platingInformation: "Plating Information",
    noPlatingInformation: "No plating information available",
    qualityControlInformation: "Quality Control Information",
    inspectionDate: "Inspection Date",
    inspector: "Inspector",
    defectType: "Defect Type",
    surfaceDefect: "Surface Defect",
    affectedQuantity: "Affected Quantity",
    repairability: "Repairability",
    notRepairable: "Not Repairable",
    viewFullDetails: "View Full Details",
    productQRCode: "Product QR Code",
    scanQRCodeToTrack: "Scan QR Code to Track Product",
  },
  vi: {
    // Navigation
    dashboard: "Tổng quan",
    warehouse: "Nhà kho",
    employees: "Nhân viên",
    requests: "Yêu cầu",
    production: "Sản xuất",
    
    // Notifications
    notifications: "Thông báo",
    markAllAsRead: "Đánh dấu tất cả đã đọc",
    noNotifications: "Không có thông báo",
    viewAllNotifications: "Xem tất cả thông báo",
    allNotificationsRead: "Tất cả thông báo đã được đánh dấu là đã đọc",
    markAsRead: "Đánh dấu đã đọc",
    allNotifications: "Tất cả thông báo",
    unread: "Chưa đọc",
    notificationsList:"Danh sách thông báo",
    requestNotifications: "Thông báo yêu cầu",
    systemNotifications: "Thông báo hệ thống",
    relatedRequest:"Yêu cầu liên quan",
    requestInfoNotAvailable:"Thông tin yêu cầu không khả dụng",
    noRequestDataAvailable: 'Không có dữ liệu yêu cầu',
    addMaterialRequestApproved: "Yêu cầu thêm nguyên vật liệu của bạn đã được phê duyệt",
    editMaterialRequestApproved: "Yêu cầu chỉnh sửa nguyên vật liệu của bạn đã được phê duyệt",
    deleteMaterialRequestApproved: "Yêu cầu xóa nguyên vật liệu của bạn đã được phê duyệt",
    addMaterialRequestRejected: "Yêu cầu thêm nguyên vật liệu của bạn đã bị từ chối",
    editMaterialRequestRejected: "Yêu cầu chỉnh sửa nguyên vật liệu của bạn đã bị từ chối",
    deleteMaterialRequestRejected: "Yêu cầu xóa nguyên vật liệu của bạn đã bị từ chối",
    newMaterialRequest: "Yêu cầu nguyên vật liệu mới từ",
    yourRequestApproved: "Yêu cầu {requestType} nguyên vật liệu của bạn đã được phê duyệt",
    yourRequestRejected: "Yêu cầu {requestType} nguyên vật liệu của bạn đã bị từ chối",
    
    // Toast messages
    loginSuccess: "Đăng nhập thành công",
    logoutSuccess: "Đã đăng xuất thành công",
    materialAdded: "Đã thêm nguyên vật liệu thành công",
    materialUpdated: "Đã cập nhật nguyên vật liệu thành công",
    materialDeleted: "Đã xóa nguyên vật liệu thành công",
    requestSubmitted: "Đã gửi yêu cầu thành công",
    requestApproved: "Đã phê duyệt yêu cầu thành công",
    requestRejected: "Đã từ chối yêu cầu thành công",
    operationSuccess: "Thao tác hoàn tất thành công",
    operationFailed: "Thao tác thất bại",
    validationError: "Vui lòng sửa các lỗi",
    networkError: "Lỗi kết nối. Vui lòng thử lại",
    serverError: "Lỗi máy chủ. Vui lòng thử lại sau",
    materialAddFailed: "Không thể thêm nguyên vật liệu",
    materialUpdateFailed: "Không thể cập nhật nguyên vật liệu",
    materialDeleteFailed: "Không thể xóa nguyên vật liệu",
    requestSubmitFailed: "Không thể gửi yêu cầu",
    requestProcessFailed: "Không thể xử lý yêu cầu",
    notesSavedSuccessfully: "Đã lưu ghi chú thành công",
    errorSavingNotes: "Lỗi khi lưu ghi chú",
    errorFetchingAssemblyDetails: "Lỗi khi tải thông tin lắp ráp",

    // Dashboard
    totalMaterials: "Tổng nguyên vật liệu",
    suppliers: "Nhà cung cấp",
    thisWeeksOrders: "Đơn hàng tuần này",
    systemUsers: "Người dùng hệ thống",
    materialTypesDistribution: "Phân bố loại nguyên vật liệu",
    monthlyInventoryChanges: "Thay đổi tồn kho hàng tháng",
    recentlyUpdatedMaterials: "Nguyên vật liệu cập nhật gần đây",
    viewAllMaterials: "Xem tất cả nguyên vật liệu",
    quickActions: "Thao tác nhanh",
    manageMaterials: "Quản lý nguyên vật liệu",
    exportInventoryReport: "Xuất báo cáo tồn kho",
    registerNewShipment: "Đăng ký lô hàng mới",
    addNewUser: "Thêm người dùng mới",

    // Materials
    materialsList: "Danh sách nguyên vật liệu",
    searchByPacketNo: "Tìm theo Packet No",
    searchByPartName: "Tìm theo Part Name",
    searchBySupplier: "Tìm theo Nhà cung cấp",
    searchByUpdatedBy: "Tìm theo Người cập nhật",
    searchBy: "Tìm theo",
    addMaterial: "Thêm nguyên vật liệu",
    requestAdd: "Yêu cầu thêm",
    packetNo: "Packet No",
    partName: "Tên bộ phận",
    materialCode: "Mã vật liệu",
    length: "Dày",
    width: "Rộng",
    materialType: "Loại nguyên vật liệu",
    quantity: "Số lượng",
    supplier: "Nhà cung cấp",
    updatedBy: "Cập nhật bởi",
    lastUpdated: "Cập nhật lần cuối",
    materialDetails: "Thông tin nguyên vật liệu",
    close: "Đóng",
    cancel: "Hủy",
    delete: "Xóa",
    saveChanges: "Lưu thay đổi",
    adding: "Đang thêm...",
    saving: "Đang lưu...",
    deleting: "Đang xóa...",
    editMaterial: "Sửa nguyên vật liệu",
    requestEdit: "Yêu cầu sửa",
    requestDelete: "Yêu cầu xóa",
    confirmDelete: "Xác nhận xóa",
    materialDeleteConfirm: "Bạn có chắc chắn muốn xóa nguyên vật liệu này?",
    submit: "Gửi",
    submitting: "Đang gửi...",
    requestDetails: "Yêu cầu {requestType} nguyên vật liệu",
    materialQRCode: "Mã QR nguyên vật liệu: {materialName}",
    scanQRCode: "Quét mã QR này để xem chi tiết nguyên vật liệu:",
    print: "In",
    edit: "Sửa",
    generate: "Tạo",
    generateQRCode: "Tạo mã QR",
    "is required": "là bắt buộc",
    "This packet number already exists. Packet numbers must be unique.": "Số packet này đã tồn tại. Số packet phải là duy nhất.",
    "Fill in the details for your": "Điền thông tin cho yêu cầu",
    "add": "thêm",
    "request": "của bạn",
    "This request will be sent to an administrator for approval.": "Yêu cầu này sẽ được gửi đến quản trị viên để phê duyệt.",
    
    // Requests
    materialRequests: "Yêu cầu nguyên vật liệu",
    status: "Trạng thái",
    pending: "Đang chờ",
    approved: "Đã duyệt",
    rejected: "Đã từ chối",
    id: "ID",
    type: "Loại",
    materialID: "ID nguyên vật liệu",
    user: "Người dùng",
    requestDate: "Ngày yêu cầu",
    actions: "Hành động",
    viewDetails: "Xem chi tiết",
    approve: "Duyệt",
    reject: "Từ chối",
    requestInformation: "Thông tin yêu cầu",
    requestedBy: "Người yêu cầu",
    responseDate: "Ngày phản hồi",
    processedBy: "Xử lý bởi",
    adminNotes: "Ghi chú của quản trị viên",
    requestData: "Dữ liệu yêu cầu",
    processRequest: "Xử lý yêu cầu này",
    decision: "Quyết định",
    notes: "Ghi chú (Tùy chọn)",
    notesPlaceholder: "Giải thích quyết định của bạn (sẽ hiển thị cho người yêu cầu)",
    approveRequest: "Duyệt yêu cầu",
    rejectRequest: "Từ chối yêu cầu",
    processing: "Đang xử lý...",
    "Request ID": "ID Yêu cầu",
    "Error loading requests": "Lỗi khi tải yêu cầu",
    "requests found": "yêu cầu được tìm thấy",
    "No": "Không có",
    "Request Details": "Chi tiết yêu cầu",
    "No request data available": "Không có dữ liệu yêu cầu",
    "Error parsing request data": "Lỗi phân tích dữ liệu yêu cầu",
    "Raw data type": "Loại dữ liệu thô",
    "First 100 chars": "100 ký tự đầu tiên",
    "No request selected": "Không có yêu cầu nào được chọn",
    "Error processing request": "Lỗi khi xử lý yêu cầu",

    // Users
    employeeAdded: "Đã thêm nhân viên thành công",
    employeeUpdated: "Đã cập nhật nhân viên thành công",
    employeeDeleted: "Đã xóa nhân viên thành công",
    employeeAddFailed: "Không thể thêm nhân viên",
    employeeUpdateFailed: "Không thể cập nhật nhân viên",
    employeeDeleteFailed: "Không thể xóa nhân viên",
    usersList: "Số nhân viên",
    searchByName: "Tìm nhân viên theo tên",
    addUser: "Thêm người dùng",
    username: "Tên đăng nhập",
    fullName: "Họ và tên",
    role: "Chức vụ",
    phone: "SĐT",
    userDetails: "Chi tiết người dùng",
    editUser: "Sửa người dùng",
    password: "Mật khẩu",
    passwordEdit: "Mật khẩu (Để trống nếu giữ nguyên)",
    phoneNumber: "Số điện thoại",
    createdAt: "Ngày tạo",
    "Adding...": "Đang thêm...",
    "Password is required for new users": "Mật khẩu là bắt buộc cho người dùng mới",
    "You don't have permission to delete this user": "Bạn không có quyền xóa người dùng này",
    "User not found": "Không tìm thấy người dùng",
    "Error loading user details": "Lỗi khi tải thông tin người dùng",
    "Are you sure you want to delete this user?": "Bạn có chắc chắn muốn xóa người dùng này?",

    // Login
    inventoryManagement: "Quản lý kho",
    loginCredentials: "Nhập thông tin đăng nhập để truy cập hệ thống",
    loggingIn: "Đang đăng nhập...",
    login: "Đăng nhập",

    // Common
    noDataFound: "Không tìm thấy dữ liệu",
    loading: "Đang tải...",
    error: "Lỗi",
    retry: "Thử lại",
    dimensions: "Kích thước",
    noData: "Không có dữ liệu",
    
    // Language
    language: "Ngôn ngữ",
    english: "Tiếng Anh",
    vietnamese: "Tiếng Việt",
    logout: "Đăng xuất",

    // Warehouse
    warehouseItems: "Hàng trong kho",
    
    // Table common terms
    noRecordsFound: "Không tìm thấy bản ghi nào",
    filter: "Lọc",
    search: "Tìm kiếm",
    
    // Notifications
    newRequestNotification: "Yêu cầu {requestType} nguyên vật liệu mới từ {username}",
    requestProcessedNotification: "Yêu cầu {requestType} nguyên vật liệu của bạn đã được {status}",
    
    // Buttons
    create: "Tạo mới",
    update: "Cập nhật",
    detail: "Chi tiết",
    confirmAction: "Xác nhận",
    backToList: "Quay lại danh sách",
    
    // Batch Grouping Page
    batchGrouping: "Nhóm lô linh kiện",
    group: "Nhóm",
    ungroupedBatches: "Lô linh kiện chưa nhóm",
    groupedBatches: "Lô linh kiện đã nhóm",
    noUngroupedBatches: "Không có lô linh kiện nào chưa được nhóm",
    noGroupedBatches: "Không có lô linh kiện nào đã được nhóm",
    warehouseEntryTime: "Thời gian nhập kho",
    groupNo: "STT",
    confirmGrouping: "Xác nhận nhóm lô",
    confirmGroupingMessage: "Bạn có chắc chắn muốn nhóm các lô đã chọn?",
    selectedBatchesCount: "Số lô đã chọn",
    afterGroupingStatus: "Sau khi nhóm, trạng thái của các lô sẽ được cập nhật thành \"Sẵn sàng lắp ráp\"",
    batchQRCode: "Mã QR lô hàng",
    batchDetails: "Chi tiết lô hàng",
    assembly: "Lắp ráp",
    details: "Chi tiết",
    confirmAssembly: "Xác nhận lắp ráp nhóm này?",
    pleaseEnterPIC: "Vui lòng nhập tên PIC:",
    selectPIC: "Chọn người phụ trách",
    startTime: "Thời gian bắt đầu:",
    currentTime: "(thời gian hiện tại)",
    completionTime: "Thời gian hoàn thành:",
    plus1Hour: "+1 giờ",
    plus2Hours: "+2 giờ",
    plus4Hours: "+4 giờ",
    plus8Hours: "+8 giờ",
    custom: "Tùy chỉnh",
    estimatedCompletionTime: "Thời gian dự kiến hoàn thành",
    productQuantity: "Số lượng sản phẩm:",
    confirm: "Xác nhận",
    groupDetails: "Chi tiết nhóm #{groupId}",
    PIC: "PIC:",
    finishAndProceedToPlating: "Xong và tiến hành mạ",

    // New additions for batch grouping and production
    processProgress: "Tiến độ quy trình sản xuất",
    ungrouped: "Chưa nhóm",
    grouped: "Đã nhóm",
    assembly: "Lắp ráp",
    plating: "Đang mạ",
    completed: "Hoàn thành",
    groupQRCode: "Mã QR nhóm",
    groupQR: "QR nhóm",
    generateGroupQRCode: "Tạo mã QR nhóm",
    assembledBy: "Lắp ráp bởi",
    assemblyDate: "Ngày lắp ráp",
    totalQuantity: "Tổng số lượng",
    batchCount: "Số lượng lô",
    groupContents: "Nội dung nhóm",
    pendingBatches: "Các lô đang chờ",

    // New additions for production
    progress: "Tiến độ",
    stageBatches: "Lô trung gian",
    productionDetails: "Chi tiết sản xuất",
    platingDetails: "Chi tiết mạ",
    machineName: "Tên máy dập",
    moldCode: "Mã khuôn",
    expectedOutput: "Sản lượng dự kiến",
    actualOutput: "Sản lượng thực tế",
    startDate: "Ngày bắt đầu",
    endDate: "Ngày kết thúc",
    timePerBatch: "Thời gian mỗi lô",
    estimatedCompletion: "Thời gian dự kiến hoàn thành",
    batchesDone: "Lô đã hoàn thành",
    batchesRemaining: "Lô còn lại",
    setPlatingTime: "Đặt thời gian mạ",
    platingDate: "Ngày mạ",
    platingTime: "Giờ mạ",
    waitingForPlating: "Đang chờ mạ",
    inPlatingProcess: "Đang trong quá trình mạ",
    timeEstimation: "Ước tính thời gian",
    completePlating: "Hoàn thành mạ",
    completionDate: "Ngày hoàn thành",
    
    // New translations for updated BatchGrouping.js
    basicAssemblyInfo: "Thông tin lắp ráp cơ bản",
    productInfoAfterAssembly: "Thông tin sản phẩm sau lắp ráp",
    productName: "Tên sản phẩm",
    productCode: "Mã sản phẩm",
    enterProductName: "Nhập tên sản phẩm...",
    enterProductCode: "Nhập mã sản phẩm...",
    enterNotes: "Nhập ghi chú...",
    pleaseSelectCompletionTime: "Vui lòng chọn thời gian hoàn thành",
    hours: "Giờ",
    minutes: "Phút",
    noProductName: "Chưa có tên sản phẩm",
    noProductCode: "Chưa có mã sản phẩm",
    assemblyInfo: "Thông tin lắp ráp",
    assemblyComponents: "Thành phần lắp ráp",
    confirmPlating: "Xác nhận chuyển qua công đoạn mạ",
    confirmPlatingMessage: "Bạn có chắc chắn muốn chuyển nhóm #{groupId} sang công đoạn mạ?",
    notesWillBeTransferredToPlating: "Ghi chú này sẽ được chuyển sang công đoạn mạ",
    
    // Validation & Success Messages
    pleaseSelectAtLeastOneBatch: "Vui lòng chọn ít nhất một lô để nhóm",
    batchesGroupedSuccessfully: "Các lô đã được nhóm thành công",
    errorGroupingBatches: "Có lỗi xảy ra khi nhóm các lô",
    pleaseSelectPIC: "Vui lòng chọn PIC",
    pleaseEnterProductQuantity: "Vui lòng nhập số lượng sản phẩm",
    pleaseEnterProductName: "Vui lòng nhập tên sản phẩm",
    pleaseEnterProductCode: "Vui lòng nhập mã sản phẩm",
    pleaseEnterCompletionTime: "Vui lòng nhập thời gian hoàn thành",
    assemblyCreatedSuccessfully: "Đã tạo lắp ráp thành công",
    errorCreatingAssembly: "Có lỗi xảy ra khi tạo lắp ráp",
    successfullyProceededToPlating: "Đã chuyển sang mạ thành công",
    errorProceedingToPlating: "Có lỗi xảy ra khi chuyển sang mạ",
    failedToFetchBatches: "Không thể tải danh sách lô hàng",
    pleaseSelectPlatingDateAndTime: "Vui lòng chọn ngày và giờ mạ",
    pleaseSelectAtLeastOneBatchForPlating: "Vui lòng chọn ít nhất một lô để mạ",
    platingInfoUpdatedSuccessfully: "Thông tin mạ đã được cập nhật thành công",
    errorUpdatingPlatingInfo: "Lỗi cập nhật thông tin mạ",

    // Warehouse Stock Check
    "Kiểm kho": "Kiểm kho",
    "Bắt đầu kiểm kho": "Bắt đầu kiểm kho",
    "Hoàn thành": "Hoàn thành",
    "Quét mã QR": "Quét mã QR",
    "Quét mã QR hoặc nhập mã nguyên vật liệu": "Quét mã QR hoặc nhập mã nguyên vật liệu",
    "Quét": "Quét",
    "Đặt con trỏ vào ô nhập liệu này trước khi quét": "Đặt con trỏ vào ô nhập liệu này trước khi quét",
    "Bạn không cần phải nhấp vào ô nhập liệu. Chỉ cần quét trực tiếp mã QR trên vật liệu.": "Bạn không cần phải nhấp vào ô nhập liệu. Chỉ cần quét trực tiếp mã QR trên vật liệu.",
    "Sẵn sàng quét": "Sẵn sàng quét",
    "Sẵn sàng nhận dữ liệu từ máy quét...": "Sẵn sàng nhận dữ liệu từ máy quét...",
    "Tổng kết kiểm kho": "Tổng kết kiểm kho",
    "Tổng số nguyên vật liệu": "Tổng số nguyên vật liệu",
    "Đã kiểm tra": "Đã kiểm tra",
    "Chưa kiểm tra": "Chưa kiểm tra",
    "Xem danh sách chưa kiểm tra": "Xem danh sách chưa kiểm tra",
    "Kiểm tra lại": "Kiểm tra lại",
    "Tìm kiếm nguyên vật liệu": "Tìm kiếm nguyên vật liệu",
    "Không tìm thấy nguyên vật liệu. Vui lòng thử lại": "Không tìm thấy nguyên vật liệu. Vui lòng thử lại",
    "Nguyên vật liệu đã kiểm tra": "Nguyên vật liệu đã kiểm tra",
    "Lỗi khi quét mã QR. Vui lòng thử lại.": "Lỗi khi quét mã QR. Vui lòng thử lại.",
    "đã được kiểm tra": "đã được kiểm tra",
    "Trạng thái": "Trạng thái",

    // Product Warehouse
    productWarehouse: "Kho Sản Phẩm",
    searchProducts: "Tìm kiếm sản phẩm",
    qualityStatus: "Trạng Thái Chất Lượng",
    defectCount: "Số Lượng Lỗi",
    usableCount: "Số Lượng Sử Dụng Được",
    statusUpdatedSuccessfully: "Cập nhật trạng thái thành công",
    errorUpdatingStatus: "Lỗi khi cập nhật trạng thái",
    pleaseSelectStatus: "Vui lòng chọn trạng thái",
    pleaseEnterQrCode: "Vui lòng nhập mã QR",
    invalidQrData: "Dữ liệu QR không hợp lệ",
    invalidQrFormat: "Định dạng QR không hợp lệ",
    productDataNotFound: "Không tìm thấy dữ liệu sản phẩm",
    errorFetchingProductDetails: "Lỗi khi lấy thông tin sản phẩm",
    scanQrCode: "Quét Mã QR",
    generateQrCode: "Tạo Mã QR",
    qualityCheck: "Kiểm Tra Chất Lượng",
    waitingForCheck: "Chờ Kiểm Tra",
    shipped: "Đã Giao Hàng",
    reserved: "Đã Đặt Trước",
    inStock: "Còn Hàng",
    defective: "Lỗi",
    
    // Product Detail
    backToWarehouse: "Quay Lại Kho",
    productNotFound: "Không Tìm Thấy Sản Phẩm",
    productDoesNotExist: "Sản phẩm này không tồn tại",
    productDetails: "Chi Tiết Sản Phẩm",
    manufacturingInfo: "Thông Tin Sản Xuất",
    groupId: "Mã Nhóm",
    createdBy: "Tạo Bởi",
    overview: "Tổng Quan",
    materialInfo: "Thông Tin Nguyên Liệu",
    productionInfo: "Thông Tin Sản Xuất",
    assemblyInfo: "Thông Tin Lắp Ráp",
    platingInfo: "Thông Tin Mạ",
    manufacturingTimeline: "Lịch Trình Sản Xuất",
    rawMaterial: "Nguyên Liệu Thô",
    material: "Nguyên Liệu",
    machine: "Máy",
    finalProduct: "Sản Phẩm Cuối Cùng",

    // Product Warehouse - Additional translations
    productName: "Tên Sản Phẩm",
    productCode: "Mã Sản Phẩm",
    quantity: "Số Lượng",
    status: "Trạng Thái",
    qualityStatus: "Trạng Thái Chất Lượng",
    defectCount: "Số Lượng Lỗi",
    usableCount: "Số Lượng Sử Dụng Được",
    waitingForCheck: "Chờ Kiểm Tra",
    ok: "OK",
    ng: "NG",
    shipped: "Đã Giao Hàng",
    reserved: "Đã Đặt Trước",
    inStock: "Còn Hàng",
    defective: "Lỗi",
    all: "Tất Cả",
    today: "Hôm Nay",
    thisWeek: "Tuần Này",
    thisMonth: "Tháng Này",
    last30Days: "30 Ngày Gần Đây",
    filterByStatus: "Lọc Theo Trạng Thái",
    filterByDate: "Lọc Theo Ngày",
    searchPlaceholder: "Tìm kiếm theo tên hoặc mã sản phẩm...",
    noProductsFound: "Không tìm thấy sản phẩm",
    productDetails: "Chi Tiết Sản Phẩm",
    updateStatus: "Cập Nhật Trạng Thái",
    save: "Lưu",
    cancel: "Hủy",
    generateQR: "Tạo Mã QR",
    scanQR: "Quét Mã QR",
    enterQRCode: "Nhập Mã QR",
    submit: "Gửi",
    qualityCheck: "Kiểm Tra Chất Lượng",
    qualityCheckStatus: "Trạng Thái Kiểm Tra",
    qualityCheckDate: "Ngày Kiểm Tra",
    qualityCheckBy: "Kiểm Tra Bởi",
    qualityCheckNotes: "Ghi Chú Kiểm Tra",
    manufacturingDate: "Ngày Sản Xuất",
    manufacturingBy: "Sản Xuất Bởi",
    assemblyDate: "Ngày Lắp Ráp",
    assemblyBy: "Lắp Ráp Bởi",
    platingDate: "Ngày Mạ",
    platingBy: "Mạ Bởi",
    completionDate: "Ngày Hoàn Thành",
    completionBy: "Hoàn Thành Bởi",
    history: "Lịch Sử",
    notes: "Ghi Chú",
    noHistory: "Không có lịch sử",
    noNotes: "Không có ghi chú",
    statusHistory: "Lịch Sử Trạng Thái",
    date: "Ngày",
    changedBy: "Thay Đổi Bởi",
    fromStatus: "Từ Trạng Thái",
    toStatus: "Đến Trạng Thái",
    reason: "Lý Do",
    noStatusHistory: "Không có lịch sử trạng thái",
    finishedProducts: "Sản Phẩm Hoàn Thành",
    reportSettings: "Cài Đặt Báo Cáo",
    allStatuses: "Tất Cả Trạng Thái",
    statusOK: "OK",
    statusNG: "NG",
    statusPending: "Đang Chờ",
    statusShipped: "Đã Giao Hàng",
    statusReserved: "Đã Đặt Trước",
    allDates: "Tất Cả Ngày",
    lastWeek: "Tuần Trước",
    lastMonth: "Tháng Trước",
    resetFilters: "Đặt Lại Bộ Lọc",
    batchId: "Mã Lô",
    currentStatus: "Trạng Thái Hiện Tại",
    newStatus: "Trạng Thái Mới",
    statusInStock: "Còn Hàng",
    statusDefective: "Lỗi",
    saveStatus: "Lưu Trạng Thái",
    productHistory: "Lịch Sử Sản Phẩm",
    materialInformation: "Thông Tin Nguyên Liệu",
    materialName: "Tên Nguyên Liệu",
    noMaterialInformation: "Không có thông tin nguyên liệu",
    productionInformation: "Thông Tin Sản Xuất",
    mold: "Khuôn",
    operator: "Người Vận Hành",
    noProductionInformation: "Không có thông tin sản xuất",
    assemblyInformation: "Thông Tin Lắp Ráp",
    noAssemblyInformation: "Không có thông tin lắp ráp",
    platingInformation: "Thông Tin Mạ",
    noPlatingInformation: "Không có thông tin mạ",
    qualityControlInformation: "Thông Tin Kiểm Soát Chất Lượng",
    inspectionDate: "Ngày Kiểm Tra",
    inspector: "Người Kiểm Tra",
    defectType: "Loại Lỗi",
    surfaceDefect: "Lỗi Bề Mặt",
    affectedQuantity: "Số Lượng Bị Ảnh Hưởng",
    repairability: "Khả Năng Sửa Chữa",
    notRepairable: "Không Thể Sửa Chữa",
    viewFullDetails: "Xem Chi Tiết Đầy Đủ",
    productQRCode: "Mã QR Sản Phẩm",
    scanQRCodeToTrack: "Quét Mã QR Để Theo Dõi Sản Phẩm",
  }
};

// Create the context
const LanguageContext = createContext();

// Create a provider component
export const LanguageProvider = ({ children }) => {
  // Get saved language from localStorage or default to English
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'en';
  });

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Toggle language function
  const toggleLanguage = () => {
    setLanguage(prevLang => prevLang === 'en' ? 'vi' : 'en');
  };

  // Function to get a translation
  const translate = (key, replacements = {}) => {
    if (!key) return '';
    
    const translation = translations[language][key] || key;
    
    // Handle replacements for dynamic content
    if (Object.keys(replacements).length > 0) {
      return Object.entries(replacements).reduce(
        (str, [key, value]) => str.replace(`{${key}}`, value),
        translation
      );
    }
    
    return translation;
  };

  // Provide the language state and functions to children
  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t: translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};